/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_camshare_CamshareClient */

#ifndef _Included_com_qpidnetwork_camshare_CamshareClient
#define _Included_com_qpidnetwork_camshare_CamshareClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    GobalInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_camshare_CamshareClient_GobalInit
  (JNIEnv *, jclass);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    SetLogDirPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_camshare_CamshareClient_SetLogDirPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    Create
 * Signature: (Lcom/qpidnetwork/camshare/CamshareClientJniCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_camshare_CamshareClient_Create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_camshare_CamshareClient_Destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    SetRecordFilePath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_camshare_CamshareClient_SetRecordFilePath
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    Login
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_camshare_CamshareClient_Login
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    MakeCall
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_camshare_CamshareClient_MakeCall
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    Hangup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_qpidnetwork_camshare_CamshareClient_Hangup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_qpidnetwork_camshare_CamshareClient
 * Method:    Stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_qpidnetwork_camshare_CamshareClient_Stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
